# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trojsten_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='fromdate',
            field=models.DateField(default=datetime.datetime(2016, 4, 6, 20, 52, 35, 680194)),
        ),
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='todate',
            field=models.DateField(default=datetime.datetime(2016, 4, 6, 20, 52, 35, 680227)),
        ),
        migrations.AddField(
            model_name='event',
            name='wholeday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trojsten_calendar.CategoryGroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trojsten_calendar.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organized_by',
            field=models.ManyToManyField(to='trojsten_calendar.Group'),
        ),
    ]
