# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trojsten_calendar', '0003_auto_20160409_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fromdate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='todate',
            new_name='start',
        ),
    ]
