# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trojsten_calendar', '0004_auto_20160410_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='wholeday',
            new_name='allDay',
        ),
    ]
