# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trojsten_calendar', '0006_auto_20160410_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organized_by',
            new_name='group',
        ),
    ]
