# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojsten_calendar', '0007_auto_20160412_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group',
            new_name='groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='trojsten_calendar.Category'),
        ),
    ]
