# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojsten_calendar', '0009_icscalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='icscalendar',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
